all: TestStringLinkedList

TestStringLinkedList: StringLinkedList.cpp TestStringLinkedList.cpp
	g++ StringLinkedList.cpp TestStringLinkedList.cpp -o TestStringLinkedList

clean:
	rm TestStringLinkedList


